// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package bulling
//

// Package bulling is a generated GoMock package.
package bulling

import (
	context "context"
	reflect "reflect"

	stats "github.com/reijo1337/ToxicBot/internal/features/stats"
	message "github.com/reijo1337/ToxicBot/internal/message"
	gomock "go.uber.org/mock/gomock"
)

// MockmessageGenerator is a mock of messageGenerator interface.
type MockmessageGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockmessageGeneratorMockRecorder
	isgomock struct{}
}

// MockmessageGeneratorMockRecorder is the mock recorder for MockmessageGenerator.
type MockmessageGeneratorMockRecorder struct {
	mock *MockmessageGenerator
}

// NewMockmessageGenerator creates a new mock instance.
func NewMockmessageGenerator(ctrl *gomock.Controller) *MockmessageGenerator {
	mock := &MockmessageGenerator{ctrl: ctrl}
	mock.recorder = &MockmessageGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageGenerator) EXPECT() *MockmessageGeneratorMockRecorder {
	return m.recorder
}

// GetMessageText mocks base method.
func (m *MockmessageGenerator) GetMessageText(replyTo string, aiChance float32) message.GenerationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageText", replyTo, aiChance)
	ret0, _ := ret[0].(message.GenerationResult)
	return ret0
}

// GetMessageText indicates an expected call of GetMessageText.
func (mr *MockmessageGeneratorMockRecorder) GetMessageText(replyTo, aiChance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageText", reflect.TypeOf((*MockmessageGenerator)(nil).GetMessageText), replyTo, aiChance)
}

// GetMessageTextWithHistory mocks base method.
func (m *MockmessageGenerator) GetMessageTextWithHistory(history []message.HistoryMessage, replyTo string, aiChance float32) message.GenerationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageTextWithHistory", history, replyTo, aiChance)
	ret0, _ := ret[0].(message.GenerationResult)
	return ret0
}

// GetMessageTextWithHistory indicates an expected call of GetMessageTextWithHistory.
func (mr *MockmessageGeneratorMockRecorder) GetMessageTextWithHistory(history, replyTo, aiChance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageTextWithHistory", reflect.TypeOf((*MockmessageGenerator)(nil).GetMessageTextWithHistory), history, replyTo, aiChance)
}

// MockstatIncer is a mock of statIncer interface.
type MockstatIncer struct {
	ctrl     *gomock.Controller
	recorder *MockstatIncerMockRecorder
	isgomock struct{}
}

// MockstatIncerMockRecorder is the mock recorder for MockstatIncer.
type MockstatIncerMockRecorder struct {
	mock *MockstatIncer
}

// NewMockstatIncer creates a new mock instance.
func NewMockstatIncer(ctrl *gomock.Controller) *MockstatIncer {
	mock := &MockstatIncer{ctrl: ctrl}
	mock.recorder = &MockstatIncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatIncer) EXPECT() *MockstatIncerMockRecorder {
	return m.recorder
}

// Inc mocks base method.
func (m *MockstatIncer) Inc(ctx context.Context, chatID, userID int64, op stats.OperationType, opts ...stats.Option) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, userID, op}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockstatIncerMockRecorder) Inc(ctx, chatID, userID, op any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, userID, op}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockstatIncer)(nil).Inc), varargs...)
}
