// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package on_voice
//

// Package on_voice is a generated GoMock package.
package on_voice

import (
	context "context"
	reflect "reflect"

	chathistory "github.com/reijo1337/ToxicBot/internal/features/chathistory"
	stats "github.com/reijo1337/ToxicBot/internal/features/stats"
	gomock "go.uber.org/mock/gomock"
	telebot "gopkg.in/telebot.v3"
)

// MockvoicesRepository is a mock of voicesRepository interface.
type MockvoicesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvoicesRepositoryMockRecorder
	isgomock struct{}
}

// MockvoicesRepositoryMockRecorder is the mock recorder for MockvoicesRepository.
type MockvoicesRepositoryMockRecorder struct {
	mock *MockvoicesRepository
}

// NewMockvoicesRepository creates a new mock instance.
func NewMockvoicesRepository(ctrl *gomock.Controller) *MockvoicesRepository {
	mock := &MockvoicesRepository{ctrl: ctrl}
	mock.recorder = &MockvoicesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvoicesRepository) EXPECT() *MockvoicesRepositoryMockRecorder {
	return m.recorder
}

// GetEnabledVoices mocks base method.
func (m *MockvoicesRepository) GetEnabledVoices() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledVoices")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledVoices indicates an expected call of GetEnabledVoices.
func (mr *MockvoicesRepositoryMockRecorder) GetEnabledVoices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledVoices", reflect.TypeOf((*MockvoicesRepository)(nil).GetEnabledVoices))
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
	isgomock struct{}
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *Mocklogger) Error(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", arg0, arg1)
}

// Error indicates an expected call of Error.
func (mr *MockloggerMockRecorder) Error(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mocklogger)(nil).Error), arg0, arg1)
}

// Warn mocks base method.
func (m *Mocklogger) Warn(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0, arg1)
}

// Warn indicates an expected call of Warn.
func (mr *MockloggerMockRecorder) Warn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*Mocklogger)(nil).Warn), arg0, arg1)
}

// WithError mocks base method.
func (m *Mocklogger) WithError(arg0 context.Context, arg1 error) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithError", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithError indicates an expected call of WithError.
func (mr *MockloggerMockRecorder) WithError(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithError", reflect.TypeOf((*Mocklogger)(nil).WithError), arg0, arg1)
}

// WithField mocks base method.
func (m *Mocklogger) WithField(arg0 context.Context, arg1 string, arg2 any) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithField", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithField indicates an expected call of WithField.
func (mr *MockloggerMockRecorder) WithField(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithField", reflect.TypeOf((*Mocklogger)(nil).WithField), arg0, arg1, arg2)
}

// Mockrandomizer is a mock of randomizer interface.
type Mockrandomizer struct {
	ctrl     *gomock.Controller
	recorder *MockrandomizerMockRecorder
	isgomock struct{}
}

// MockrandomizerMockRecorder is the mock recorder for Mockrandomizer.
type MockrandomizerMockRecorder struct {
	mock *Mockrandomizer
}

// NewMockrandomizer creates a new mock instance.
func NewMockrandomizer(ctrl *gomock.Controller) *Mockrandomizer {
	mock := &Mockrandomizer{ctrl: ctrl}
	mock.recorder = &MockrandomizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrandomizer) EXPECT() *MockrandomizerMockRecorder {
	return m.recorder
}

// Float32 mocks base method.
func (m *Mockrandomizer) Float32() float32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Float32")
	ret0, _ := ret[0].(float32)
	return ret0
}

// Float32 indicates an expected call of Float32.
func (mr *MockrandomizerMockRecorder) Float32() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Float32", reflect.TypeOf((*Mockrandomizer)(nil).Float32))
}

// Intn mocks base method.
func (m *Mockrandomizer) Intn(n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intn", n)
	ret0, _ := ret[0].(int)
	return ret0
}

// Intn indicates an expected call of Intn.
func (mr *MockrandomizerMockRecorder) Intn(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intn", reflect.TypeOf((*Mockrandomizer)(nil).Intn), n)
}

// Mockdownloader is a mock of downloader interface.
type Mockdownloader struct {
	ctrl     *gomock.Controller
	recorder *MockdownloaderMockRecorder
	isgomock struct{}
}

// MockdownloaderMockRecorder is the mock recorder for Mockdownloader.
type MockdownloaderMockRecorder struct {
	mock *Mockdownloader
}

// NewMockdownloader creates a new mock instance.
func NewMockdownloader(ctrl *gomock.Controller) *Mockdownloader {
	mock := &Mockdownloader{ctrl: ctrl}
	mock.recorder = &MockdownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdownloader) EXPECT() *MockdownloaderMockRecorder {
	return m.recorder
}

// FileByID mocks base method.
func (m *Mockdownloader) FileByID(fileID string) (telebot.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileByID", fileID)
	ret0, _ := ret[0].(telebot.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileByID indicates an expected call of FileByID.
func (mr *MockdownloaderMockRecorder) FileByID(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileByID", reflect.TypeOf((*Mockdownloader)(nil).FileByID), fileID)
}

// MockstatIncer is a mock of statIncer interface.
type MockstatIncer struct {
	ctrl     *gomock.Controller
	recorder *MockstatIncerMockRecorder
	isgomock struct{}
}

// MockstatIncerMockRecorder is the mock recorder for MockstatIncer.
type MockstatIncerMockRecorder struct {
	mock *MockstatIncer
}

// NewMockstatIncer creates a new mock instance.
func NewMockstatIncer(ctrl *gomock.Controller) *MockstatIncer {
	mock := &MockstatIncer{ctrl: ctrl}
	mock.recorder = &MockstatIncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatIncer) EXPECT() *MockstatIncerMockRecorder {
	return m.recorder
}

// Inc mocks base method.
func (m *MockstatIncer) Inc(ctx context.Context, chatID, userID int64, op stats.OperationType, opts ...stats.Option) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, userID, op}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockstatIncerMockRecorder) Inc(ctx, chatID, userID, op any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, userID, op}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockstatIncer)(nil).Inc), varargs...)
}

// MockhistoryBuffer is a mock of historyBuffer interface.
type MockhistoryBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockhistoryBufferMockRecorder
	isgomock struct{}
}

// MockhistoryBufferMockRecorder is the mock recorder for MockhistoryBuffer.
type MockhistoryBufferMockRecorder struct {
	mock *MockhistoryBuffer
}

// NewMockhistoryBuffer creates a new mock instance.
func NewMockhistoryBuffer(ctrl *gomock.Controller) *MockhistoryBuffer {
	mock := &MockhistoryBuffer{ctrl: ctrl}
	mock.recorder = &MockhistoryBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhistoryBuffer) EXPECT() *MockhistoryBufferMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockhistoryBuffer) Add(chatID int64, e chathistory.Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", chatID, e)
}

// Add indicates an expected call of Add.
func (mr *MockhistoryBufferMockRecorder) Add(chatID, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockhistoryBuffer)(nil).Add), chatID, e)
}

// MockbotReplier is a mock of botReplier interface.
type MockbotReplier struct {
	ctrl     *gomock.Controller
	recorder *MockbotReplierMockRecorder
	isgomock struct{}
}

// MockbotReplierMockRecorder is the mock recorder for MockbotReplier.
type MockbotReplierMockRecorder struct {
	mock *MockbotReplier
}

// NewMockbotReplier creates a new mock instance.
func NewMockbotReplier(ctrl *gomock.Controller) *MockbotReplier {
	mock := &MockbotReplier{ctrl: ctrl}
	mock.recorder = &MockbotReplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbotReplier) EXPECT() *MockbotReplierMockRecorder {
	return m.recorder
}

// Reply mocks base method.
func (m *MockbotReplier) Reply(to *telebot.Message, what any, opts ...any) (*telebot.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{to, what}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reply", varargs...)
	ret0, _ := ret[0].(*telebot.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reply indicates an expected call of Reply.
func (mr *MockbotReplierMockRecorder) Reply(to, what any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{to, what}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockbotReplier)(nil).Reply), varargs...)
}
